2023-10-07 16:48:52,107 INFO [streaming_server.py:820] {'encoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx', 'decoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx', 'joiner': './sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx', 'paraformer_encoder': None, 'paraformer_decoder': None, 'tokens': './sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt', 'sample_rate': 16000, 'feat_dim': 80, 'provider': 'cpu', 'decoding_method': 'greedy_search', 'num_active_paths': 4, 'use_endpoint': 1, 'rule1_min_trailing_silence': 2.4, 'rule2_min_trailing_silence': 1.2, 'rule3_min_utterance_length': 20, 'hotwords_file': '', 'hotwords_score': 1.5, 'port': 6006, 'nn_pool_size': 1, 'max_batch_size': 50, 'max_wait_ms': 10, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'num_threads': 2, 'certificate': None, 'doc_root': 'web'}
2023-10-07 16:48:54,578 INFO [streaming_server.py:628] No certificate provided
2023-10-07 16:48:54,579 INFO [server.py:711] server listening on [::]:6006
2023-10-07 16:48:54,581 INFO [server.py:711] server listening on 0.0.0.0:6006
2023-10-07 16:48:54,581 INFO [streaming_server.py:654] Please visit one of the following addresses:

  http://localhost:6006

Since you are not providing a certificate, you cannot use your microphone from within the browser using public IP addresses. Only localhost can be used.You also cannot use 0.0.0.0 or 127.0.0.1
2023-10-07 16:48:57,960 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:57,960 INFO [server.py:268] connection closed
2023-10-07 16:48:58,022 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,023 INFO [server.py:268] connection closed
2023-10-07 16:48:58,029 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,029 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,029 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,030 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,030 INFO [server.py:268] connection closed
2023-10-07 16:48:58,030 INFO [server.py:268] connection closed
2023-10-07 16:48:58,030 INFO [server.py:268] connection closed
2023-10-07 16:48:58,030 INFO [server.py:268] connection closed
2023-10-07 16:48:58,122 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,122 INFO [server.py:268] connection closed
2023-10-07 16:48:58,129 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,134 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,135 INFO [server.py:233] connection failed (200 OK)
2023-10-07 16:48:58,135 INFO [server.py:268] connection closed
2023-10-07 16:48:58,135 INFO [server.py:268] connection closed
2023-10-07 16:48:58,135 INFO [server.py:268] connection closed
2023-10-07 16:48:58,960 INFO [server.py:646] connection open
2023-10-07 16:48:58,961 INFO [streaming_server.py:695] Connected: ('::1', 59541, 0, 0). Number of connections: 1/500
2023-10-07 16:48:59,551 INFO [streaming_server.py:679] Disconnected: ('::1', 59541, 0, 0). Number of connections: 0/500
2023-10-07 16:48:59,551 ERROR [server.py:242] connection handler failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 672, in handle_connection
    await self.handle_connection_impl(socket)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 744, in handle_connection_impl
    await socket.send(json.dumps(message))
                                 ^^^^^^^
UnboundLocalError: cannot access local variable 'message' where it is not associated with a value
2023-10-07 16:48:59,557 INFO [server.py:268] connection closed
